import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'


const manrope = localFont({ src: "../assets/fonts/Manrope/Manrope-VariableFont_wght.ttf" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>{children}</body>
    </html>
  )
}
